// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

#nullable disable

namespace api.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api.Data.Entities.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApprovalRule")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("all");

                    b.Property<bool>("Archived")
                        .HasColumnType("bit");

                    b.Property<string>("ArtDriveFileId")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("BandId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BandId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Album", (string)null);
                });

            modelBuilder.Entity("api.Data.Entities.AlbumProposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("ProposedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("ProposedBy");

                    b.HasIndex("SongId");

                    b.ToTable("AlbumProposal", (string)null);
                });

            modelBuilder.Entity("api.Data.Entities.AlbumProposalDecision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("ProposalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("ProposalId", "MemberId")
                        .IsUnique();

                    b.ToTable("AlbumProposalDecision", (string)null);
                });

            modelBuilder.Entity("api.Data.Entities.AlbumProposalReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("EndMs")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("ProposalId")
                        .HasColumnType("int");

                    b.Property<int>("StartMs")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("ProposalId");

                    b.ToTable("AlbumProposalReview", (string)null);
                });

            modelBuilder.Entity("api.Data.Entities.AlbumTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<int?>("ProposalId")
                        .HasColumnType("int");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProposalId");

                    b.HasIndex("SongId");

                    b.HasIndex("AlbumId", "SongId")
                        .IsUnique();

                    b.ToTable("AlbumTrack", (string)null);
                });

            modelBuilder.Entity("api.Data.Entities.Band", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("DriveFolderId")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("DriveFolderName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Genre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Image")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("OwnerMemberId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerMemberId");

                    b.ToTable("Band", (string)null);
                });

            modelBuilder.Entity("api.Data.Entities.BandInvite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("BandId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .IsUnicode(false)
                        .HasColumnType("varchar(320)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("BandId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedBy");

                    b.ToTable("BandInvite", (string)null);
                });

            modelBuilder.Entity("api.Data.Entities.BandMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BandId")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("member");

                    b.HasKey("Id");

                    b.HasIndex("BandId");

                    b.HasIndex("MemberId");

                    b.ToTable("BandMember", (string)null);
                });

            modelBuilder.Entity("api.Data.Entities.GoogleAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId")
                        .IsUnique();

                    b.ToTable("GoogleAccount", (string)null);
                });

            modelBuilder.Entity("api.Data.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .IsUnicode(false)
                        .HasColumnType("varchar(320)");

                    b.Property<string>("Fullname")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("GoogleSubject")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("UserIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_Members");

                    b.HasIndex("Email");

                    b.HasIndex("GoogleSubject");

                    b.ToTable("Member", (string)null);
                });

            modelBuilder.Entity("api.Data.Entities.MemberRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("RoleId");

                    b.ToTable("MemberRole", (string)null);
                });

            modelBuilder.Entity("api.Data.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("CreatedFor")
                        .HasColumnType("int");

                    b.Property<string>("RoleDescription")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedFor");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("api.Data.Entities.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PreviousVersion")
                        .HasColumnType("int");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("URL");

                    b.Property<int?>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UploadedBy");

                    b.ToTable("Song", (string)null);
                });

            modelBuilder.Entity("api.Data.Entities.SongIdentifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BandId")
                        .HasColumnType("int");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BandId");

                    b.HasIndex("SongId");

                    b.ToTable("SongIdentifier", (string)null);
                });

            modelBuilder.Entity("api.Data.Entities.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id", "MemberId", "SongId");

                    b.HasIndex("MemberId");

                    b.HasIndex("SongId");

                    b.ToTable("Vote", (string)null);
                });

            modelBuilder.Entity("api.Data.Entities.Band", b =>
                {
                    b.HasOne("api.Data.Entities.Member", "OwnerMember")
                        .WithMany("OwnedBands")
                        .HasForeignKey("OwnerMemberId")
                        .HasConstraintName("FK_Band_OwnerMember");

                    b.Navigation("OwnerMember");
                });

            modelBuilder.Entity("api.Data.Entities.BandInvite", b =>
                {
                    b.HasOne("api.Data.Entities.Band", "Band")
                        .WithMany("BandInvites")
                        .HasForeignKey("BandId")
                        .IsRequired()
                        .HasConstraintName("FK_BandInvite_Band");

                    b.HasOne("api.Data.Entities.Member", "CreatedByNavigation")
                        .WithMany("CreatedInvites")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_BandInvite_Member");

                    b.Navigation("Band");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("api.Data.Entities.BandMember", b =>
                {
                    b.HasOne("api.Data.Entities.Band", "Band")
                        .WithMany("BandMembers")
                        .HasForeignKey("BandId")
                        .IsRequired()
                        .HasConstraintName("FK_BandMember_Band");

                    b.HasOne("api.Data.Entities.Member", "Member")
                        .WithMany("BandMembers")
                        .HasForeignKey("MemberId")
                        .IsRequired()
                        .HasConstraintName("FK_BandMember_Member");

                    b.Navigation("Band");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("api.Data.Entities.GoogleAccount", b =>
                {
                    b.HasOne("api.Data.Entities.Member", "Member")
                        .WithOne("GoogleAccount")
                        .HasForeignKey("api.Data.Entities.GoogleAccount", "MemberId")
                        .IsRequired()
                        .HasConstraintName("FK_GoogleAccount_Member");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("api.Data.Entities.MemberRole", b =>
                {
                    b.HasOne("api.Data.Entities.Member", "Member")
                        .WithMany("MemberRoles")
                        .HasForeignKey("MemberId")
                        .IsRequired()
                        .HasConstraintName("FK_MemberRole_Member");

                    b.HasOne("api.Data.Entities.Role", "Role")
                        .WithMany("MemberRoles")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_MemberRole_Role");

                    b.Navigation("Member");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("api.Data.Entities.Role", b =>
                {
                    b.HasOne("api.Data.Entities.Member", "CreatedByNavigation")
                        .WithMany("Roles")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Role_Member");

                    b.HasOne("api.Data.Entities.Band", "CreatedForNavigation")
                        .WithMany("Roles")
                        .HasForeignKey("CreatedFor")
                        .IsRequired()
                        .HasConstraintName("FK_Role_Band");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("CreatedForNavigation");
                });

            modelBuilder.Entity("api.Data.Entities.Song", b =>
                {
                    b.HasOne("api.Data.Entities.Member", "UploadedByNavigation")
                        .WithMany("Songs")
                        .HasForeignKey("UploadedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Song_Member");

                    b.Navigation("UploadedByNavigation");
                });

            modelBuilder.Entity("api.Data.Entities.SongIdentifier", b =>
                {
                    b.HasOne("api.Data.Entities.Band", "Band")
                        .WithMany("SongIdentifiers")
                        .HasForeignKey("BandId")
                        .IsRequired()
                        .HasConstraintName("FK_SongIdentifier_Band");

                    b.HasOne("api.Data.Entities.Song", "Song")
                        .WithMany("SongIdentifiers")
                        .HasForeignKey("SongId")
                        .IsRequired()
                        .HasConstraintName("FK_SongIdentifier_Song");

                    b.Navigation("Band");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("api.Data.Entities.Vote", b =>
                {
                    b.HasOne("api.Data.Entities.Member", "Member")
                        .WithMany("Votes")
                        .HasForeignKey("MemberId")
                        .IsRequired()
                        .HasConstraintName("FK_Vote_Member");

                    b.HasOne("api.Data.Entities.Song", "Song")
                        .WithMany("Votes")
                        .HasForeignKey("SongId")
                        .IsRequired()
                        .HasConstraintName("FK_Vote_Song");

                    b.Navigation("Member");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("api.Data.Entities.Album", b =>
                {
                    b.HasOne("api.Data.Entities.Band", "Band")
                        .WithMany("Albums")
                        .HasForeignKey("BandId")
                        .IsRequired()
                        .HasConstraintName("FK_Album_Band");

                    b.HasOne("api.Data.Entities.Member", "CreatedByNavigation")
                        .WithMany("CreatedAlbums")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Album_Member");

                    b.Navigation("Band");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("api.Data.Entities.AlbumProposal", b =>
                {
                    b.HasOne("api.Data.Entities.Album", "Album")
                        .WithMany("Proposals")
                        .HasForeignKey("AlbumId")
                        .IsRequired()
                        .HasConstraintName("FK_AlbumProposal_Album");

                    b.HasOne("api.Data.Entities.Member", "ProposedByNavigation")
                        .WithMany("AlbumProposals")
                        .HasForeignKey("ProposedBy")
                        .IsRequired()
                        .HasConstraintName("FK_AlbumProposal_Member");

                    b.HasOne("api.Data.Entities.Song", "Song")
                        .WithMany("AlbumProposals")
                        .HasForeignKey("SongId")
                        .IsRequired()
                        .HasConstraintName("FK_AlbumProposal_Song");

                    b.Navigation("Album");

                    b.Navigation("ProposedByNavigation");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("api.Data.Entities.AlbumProposalDecision", b =>
                {
                    b.HasOne("api.Data.Entities.Member", "Member")
                        .WithMany("AlbumProposalDecisions")
                        .HasForeignKey("MemberId")
                        .IsRequired()
                        .HasConstraintName("FK_AlbumProposalDecision_Member");

                    b.HasOne("api.Data.Entities.AlbumProposal", "Proposal")
                        .WithMany("Decisions")
                        .HasForeignKey("ProposalId")
                        .IsRequired()
                        .HasConstraintName("FK_AlbumProposalDecision_Proposal");

                    b.Navigation("Member");

                    b.Navigation("Proposal");
                });

            modelBuilder.Entity("api.Data.Entities.AlbumProposalReview", b =>
                {
                    b.HasOne("api.Data.Entities.Member", "Member")
                        .WithMany("AlbumProposalReviews")
                        .HasForeignKey("MemberId")
                        .IsRequired()
                        .HasConstraintName("FK_AlbumProposalReview_Member");

                    b.HasOne("api.Data.Entities.AlbumProposal", "Proposal")
                        .WithMany("Reviews")
                        .HasForeignKey("ProposalId")
                        .IsRequired()
                        .HasConstraintName("FK_AlbumProposalReview_Proposal");

                    b.Navigation("Member");

                    b.Navigation("Proposal");
                });

            modelBuilder.Entity("api.Data.Entities.AlbumTrack", b =>
                {
                    b.HasOne("api.Data.Entities.Album", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumId")
                        .IsRequired()
                        .HasConstraintName("FK_AlbumTrack_Album");

                    b.HasOne("api.Data.Entities.AlbumProposal", "Proposal")
                        .WithMany()
                        .HasForeignKey("ProposalId")
                        .HasConstraintName("FK_AlbumTrack_Proposal");

                    b.HasOne("api.Data.Entities.Song", "Song")
                        .WithMany("AlbumTracks")
                        .HasForeignKey("SongId")
                        .IsRequired()
                        .HasConstraintName("FK_AlbumTrack_Song");

                    b.Navigation("Album");

                    b.Navigation("Proposal");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("api.Data.Entities.Album", b =>
                {
                    b.Navigation("Proposals");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("api.Data.Entities.AlbumProposal", b =>
                {
                    b.Navigation("Decisions");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("api.Data.Entities.Band", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("BandInvites");

                    b.Navigation("BandMembers");

                    b.Navigation("Roles");

                    b.Navigation("SongIdentifiers");
                });

            modelBuilder.Entity("api.Data.Entities.Member", b =>
                {
                    b.Navigation("AlbumProposalDecisions");

                    b.Navigation("AlbumProposalReviews");

                    b.Navigation("AlbumProposals");

                    b.Navigation("BandMembers");

                    b.Navigation("CreatedAlbums");

                    b.Navigation("CreatedInvites");

                    b.Navigation("GoogleAccount");

                    b.Navigation("MemberRoles");

                    b.Navigation("OwnedBands");

                    b.Navigation("Roles");

                    b.Navigation("Songs");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("api.Data.Entities.Role", b =>
                {
                    b.Navigation("MemberRoles");
                });

            modelBuilder.Entity("api.Data.Entities.Song", b =>
                {
                    b.Navigation("AlbumProposals");

                    b.Navigation("AlbumTracks");

                    b.Navigation("SongIdentifiers");

                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
